version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      # Install project dependencies
      - node -v
      - npm i

  build:
    commands:
      # Build the react app
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'build'
