version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - node -v
      - npm i
      
  build:
    commands:
      - npm run build
      - aws s3 sync build/ s3://react-bukcet-yuks
      - aws cloudfront create-invalidation --distribution-id E2LS173VEP3S7C --paths /*
      
  artifacts: null
  files:
    - "**/*"
  base-directory: build
